services:
  - docker

install:
  - docker build -t ddiez/meme .

before_script:
  - git clone https://github.com/ddiez/dataset.git

script:
  - docker run meme
  - docker run -v $(pwd):/home/biodev ddiez/meme meme dataset/fasta/uniprot.fasta

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push ddiez/meme;
      VERSION=`docker run ddiez/meme printenv VERSION`;
      docker tag ddiez/meme ddiez/meme:$VERSION;
      docker push ddiez/meme:$VERSION;
    fi
